# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Mohammad Afkani
title: Physics Student
email: afkani.mohammad@gmail.com
website: afkani.ir

# Social links
twitter_username: HerrFloating
github_username:  HerrFloating
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: HerrFloating
linkedin_username: HerrFloating
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Mohammad Afkani and I'm a Physics student/researcher interested in laws of the Universe.
  curiosity made me find answers to questions in the deep nanoworld, the way it affects human being and vice-versa.
  <mark>Computation Physics</mark> and <mark>Condensed matter Physics</mark>

# Projects Section
# projects_title: Projects
    
# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education
- layout: left
  name: Kharazmi University of Tehran
  dates: 2016 - 2020
  qualification: B.Sc. Solid-State Physics
  quote: >
    Fully Funded Scholarship
  description: | # this will include new lines to allow paragraphs
    GPA: 3.2/4

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
